[versions]
agp = "8.7.2"
activityKtx = "1.9.3"
appcompat = "1.7.0"
constraintlayout = "2.2.0"
material = "1.12.0"
junit = "4.13.2"
espressoCore = "3.6.1"
extJunit = "1.2.1"

[libraries]
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }